site_name: QEMU Camp Tutorial
site_author: GTOC
site_url: https://github.com/gevico
repo_name: gevico/qemu-camp-tutorial
repo_url: https://github.com/gevico/qemu-camp-tutorial
copyright: Brought to you by <a href="https://github.com/gevico">Gevico Tech Open Community</a>. Available freely under the MIT license.

plugins:
  - md-preview:
      enable: true
      left_title: "Markdown 源码"
      right_title: "渲染输出"

markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.def_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.extra
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/man.md
        - includes/authors.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  language: zh
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to happy mode
      accent: pink
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue grey
      accent: pink
  features:
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - content.comments
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
extra_css:
  - stylesheets/extra.css

nav:
  - 主页: index.md
  - 讲义:
    - QEMU 训练营 2026:
      - 训练营介绍: tutorial/2026/index.md
      - 1. 导学阶段: tutorial/2026/ch0/index.md
      - 2. 基础阶段:
        - 本章导览: tutorial/2026/ch1/index.md
        - a. 虚拟技术发展历史: tutorial/2026/ch1/vm-history.md
        - b. QEMU 启动参数分析: tutorial/2026/ch1/qemu-startup-param.md
        - c. QEMU 启动流程分析: tutorial/2026/ch1/qemu-init.md
        - d. QEMU 面向对象建模: tutorial/2026/ch1/qemu-qom.md
    - QEMU 训练营 2025:
      - 训练营介绍: tutorial/2025/index.md
      - 1. 导学阶段: tutorial/2025/ch0/index.md
      - 2. 基础阶段:
        - 本章导览: tutorial/2025/ch1/index.md
        - a. 虚拟技术发展历史: tutorial/2025/ch1/sec1/vm-history.md
        - b. Hypervisor 技术介绍: tutorial/2025/ch1/sec2/hypervisor.md
        - c. QEMU 基本知识介绍:
          - 面向对象建模: tutorial/2025/ch1/sec3/qemu-qom.md
          - 地址空间抽象: tutorial/2025/ch1/sec3/qemu-memory-region.md
      - 3. 专业阶段:
        - 本章导览: tutorial/2025/ch2/index.md
        - a. QEMU 初始化: tutorial/2025/ch2/sec1/qemu-init.md
        - b. QEMU 加速器:
          - Tiny Code Generator:
            - TCG Translation: tutorial/2025/ch2/sec2/qemu-accel-tcg/tcg-translation.md
            - Decodetree: tutorial/2025/ch2/sec2/qemu-accel-tcg/tcg-add-guest-insn.md
            - TCG IR: tutorial/2025/ch2/sec2/qemu-accel-tcg/tcg-ir.md
          - Hypervisor: tutorial/2025/ch2/sec2/qemu-accel-kvm.md
        - c. QEMU Arch 模拟:
            - RISC-V 模拟: tutorial/2025/ch2/sec3/qemu-tcg-riscv.md
        - d. QEMU 硬件建模:
            - C 语言建模:
              - Machine 建模: tutorial/2025/ch2/sec4/c-model/machine-model.md
              - 外设建模（串口）: tutorial/2025/ch2/sec4/c-model/peripheral-model-uart.md
              - 外设建模（edu）: tutorial/2025/ch2/sec4/c-model/peripheral-model-edu.md
              - 中断建模: tutorial/2025/ch2/sec4/c-model/intr-model.md
            - Rust 建模:
              - Rust in QEMU: tutorial/2025/ch2/sec4/rust-model/rust-in-qemu.md
              - 外设建模: tutorial/2025/ch2/sec4/rust-model/peripheral-model.md
        - e. QEMU 调试:
          - 源码调试: tutorial/2025/ch2/sec5/debug-qemu.md
          - 远程调试: tutorial/2025/ch2/sec5/gdbstub.md
          - 日志调试: tutorial/2025/ch2/sec5/qemu-log.md
          - 追踪事件: tutorial/2025/ch2/sec5/trace-event.md
        - f. QEMU 测试:
            - Qtest: tutorial/2025/ch2/sec6/qtest.md
            - TCG 测试: tutorial/2025/ch2/sec6/test-tcg.md
        - g. QEMU 虚拟化实践:
            - 创建和管理虚拟机: tutorial/2025/ch2/sec7/qemu-virtual.md
            - 模拟 RISCV 虚拟化: tutorial/2025/ch2/sec7/emulate-rvh.md
      - 4. 项目阶段:
        - 本章导览: tutorial/2025/ch3/index.md
        - a. QEMU 建模 K230: tutorial/2025/ch3/sec1/k230-model.md
        - b. QEMU 测评 OS: tutorial/2025/ch3/sec2/os-test.md
      - 5. 课程附录:
        - a. Prof Level Manual: tutorial/2025/ch4/prof-level-manual.md
        - b. G233 Datasheet: tutorial/2025/ch4/g233-board-datasheet.md
      - 6. 贡献名录: tutorial/2025/ch5/contributors.md
  - 博客: blogs/index.md
  - 新闻:
    - 2026 年:
      - 01 月 07 号: news/2026/qemu-camp-update-2026-01-07.md